name: Nintendo Switch Emulator Release

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: "Source repository (owner/repo)"
        required: true
        default: "eden-emulator/Releases"
  push:
    branches:
      - main
  schedule:
    - cron: "30 1 * * *"

permissions:
  contents: write
  packages: write

jobs:
  release_emulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # 新增：强制清理旧文件目录 
      - name: Clean old assets directory 
        run: | 
          rm -rf downloaded_assets/* 
          mkdir -p downloaded_assets 
          echo "Assets directory cleaned"

      - name: Get Eden latest release info
        id: get_eden_release
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repo] = '${{ 'eden-emulator/Releases' }}'.split('/')
            const response = await github.rest.repos.getLatestRelease({
              owner: owner,
              repo: repo
            })

            // 保存所有assets信息
            const assets = response.data.assets.map(asset => {
              return {
                name: asset.name,
                url: asset.browser_download_url,
                size: asset.size,
                content_type: asset.content_type
              }
            })

            // 保存release信息
            core.setOutput('release_name', response.data.name)
            core.setOutput('release_tag', response.data.tag_name)
            core.setOutput('release_body', response.data.body)
            core.setOutput('assets', JSON.stringify(assets))

            return assets

      - name: Download Eden all assets
        id: download_eden_assets
        run: |
          mkdir -p downloaded_assets
          assets='${{ steps.get_eden_release.outputs.assets }}'

          echo "Found eden assets: $assets"

          for row in $(echo "$assets" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            
            name=$(_jq '.name')
            url=$(_jq '.url')
            
            echo "Downloading $name from $url"
            curl -L -o "downloaded_assets/$name" "$url"
            
            # 验证文件大小
            expected_size=$(_jq '.size')
            actual_size=$(wc -c < "downloaded_assets/$name")
            
            if [ "$actual_size" -lt "$expected_size" ]; then
              echo "Error: Downloaded file $name is smaller than expected ($actual_size < $expected_size)"
              exit 1
            fi
          done
      - name: Get Sudachi latest release info
        id: get_sudachi_release
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repo] = '${{ 'emuplace/sudachi.emuplace.app' }}'.split('/')
            const response = await github.rest.repos.getLatestRelease({
              owner: owner,
              repo: repo
            })

            // 保存所有assets信息
            const assets = response.data.assets.map(asset => {
              return {
                name: asset.name,
                url: asset.browser_download_url,
                size: asset.size,
                content_type: asset.content_type
              }
            })

            // 保存release信息
            core.setOutput('release_name', response.data.name)
            core.setOutput('release_tag', response.data.tag_name)
            core.setOutput('release_body', response.data.body)
            core.setOutput('assets', JSON.stringify(assets))

            return assets

      - name: Download Sudachi all assets
        id: download_sudachi_assets
        run: |
          mkdir -p downloaded_assets
          assets='${{ steps.get_sudachi_release.outputs.assets }}'

          echo "Found sudachi assets: $assets"

          for row in $(echo "$assets" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            
            old_name=$(_jq '.name')
            name="sudachi-${old_name}"
            url=$(_jq '.url')
            
            echo "Downloading $name from $url"
            curl -L -o "downloaded_assets/$name" "$url"
            
            # 验证文件大小
            expected_size=$(_jq '.size')
            actual_size=$(wc -c < "downloaded_assets/$name")
            
            if [ "$actual_size" -lt "$expected_size" ]; then
              echo "Error: Downloaded file $name is smaller than expected ($actual_size < $expected_size)"
              exit 1
            fi
          done
      # 删除 latest release 旧文件 
      - name: Delete release assets
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'latest'
            })
            const assets = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id
            })
            for (const asset of assets.data) {
              await github.rest.repos.deleteReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: asset.id
              })
            }

      - name: Create new release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          name: "latest"
          overwrite: true
          files: |
            downloaded_assets/*

      - name: Verify uploaded assets
        run: |
          echo "Successfully republished all assets"
          echo "View release at: ${{ steps.create_release.outputs.html_url }}"
