name: Nintendo Switch Emulator Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "30 1 * * *"

permissions:
  contents: write
  packages: write

jobs:
  release_emulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: eden-emulator,
              repo: Releases
            })
            return release.data

      - name: Download assets
        run: |
          for asset in ${{ steps.get_release.outputs.result.assets }}; do
            wget -O $(echo $asset | jq -r '.name') $(echo $asset | jq -r '.browser_download_url')
          done

      - name: Validate downloads
        run: |
          for file in *.apk *.zip; do
            if [ ! -f "$file" ]; then
              echo "$file 下载失败"
              exit 1
            fi
            size=$(stat -c%s "$file")
            if [ "$size" -lt 1000 ]; then
              echo "$file 文件大小异常"
              exit 1
            fi
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Eden-Android-v0.0.3-rc3-Legacy.apk
            Eden-Android-v0.0.3-rc3-Optimised.apk
            Eden-Android-v0.0.3-rc3.apk
            Eden-Windows-v0.0.3-rc3-amd64.zip
          tag_name: latest
          generate_release_notes: true
